apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: shop
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: webinar-demo/cart:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
            - name: REDIS_ADDR
              value: redis.shop:6379
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: shop
spec:
  type: ClusterIP
  selector:
    app: cart
  ports:
    - port: 8082
      targetPort: 8082
