apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: shop
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: webinar-demo/order:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: PORT
              value: "8085"
            - name: POSTGRES_DSN
              value: postgres://postgres:postgres@postgres.shop:5432/orders?sslmode=disable
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: shop
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - port: 8085
      targetPort: 8085
