apiVersion: syntheticmonitoring.ext.grafana.app/v1alpha1
kind: Check
metadata:
  name: "webshop-checkout-74160"
spec:
  job: webshop-checkout
  target: http://checkout.shop.svc.cluster.local:8083/healthz
  enabled: true
  frequency: 60000
  timeout: 5000
  probes:
    - private probe
  labels:
    - name: app
      value: webshop
    - name: service
      value: checkout
  settings:
    http:
      method: GET
      validStatusCodes:
        - 200
