apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: webinar-demo
servers: 1
agents: 1
image: rancher/k3s:v1.30.4-k3s1
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "120s"
  k3s:
    extraArgs:
      - arg: --disable=metrics-server
        nodeFilters:
          - server:*
